package io.silv.ui

enum class Language(
    val string: String,
    val code: String,
) {
    Arabic("Arabic", "sa"),
    Bengali("Bengali", "bd"),
    Bulgarian("Bulgarian", "bg"),
    Burmese("Burmese", "mm"),
    ChineseSimp("Chinese (Simplified)", "cn"),
    ChineseTrad("Chinese (Traditional)", "hk"),
    Czech("Czech", "cz"),
    Danish("Danish", "dk"),
    Dutch("Dutch", "nl"),
    English("English", "en"),
    Filipino("Filipino", "ph"),
    Finnish("Finnish", "fi"),
    French("French", "fr"),
    German("German", "de"),
    Greek("Greek", "gr"),
    Hebrew("Hebrew", "il"),
    Hindi("Hindi", "in"),
    Hungarian("Hungarian", "hu"),
    Indonesian("Indonesian", "id"),
    Italian("Italian", "it"),
    Japanese("Japanese", "jp"),
    Korean("Korean", "kr"),
    Lithuanian("Lithuanian", "lt"),
    Malay("Malay", "my"),
    Mongolian("Mongolian", "mn"),
    Polish("Polish", "pl"),
    PortugueseBr("Portuguese (Br)", "br"),
    PortuguesePt("Portuguese (Pt)", "pt"),
    Romanian("Romanian", "ro"),
    Russian("Russian", "ru"),
    Serbian("Serbian", "rs"),
    SpanishEs("Spanish (Es)", "es"),
    SpanishLATAM("Spanish (LATAM)", "mx"),
    Swedish("Swedish", "se"),
    Thai("Thai", "th"),
    Turkish("Turkish", "tr"),
    Ukrainian("Ukrainian", "ua"),
    Vietnamese("Vietnamese", "vn"),
}
