[versions]
accompanistWebview = "0.31.6-rc"
accompanistWebviewVersion = "0.30.1"
activityCompose = "1.8.1"
androidxComposeBom = "2023.10.01"
androidxCoreKtx = "1.12.0"
androidxTestEspressoCore = "3.5.1"
appcompat = "1.6.1"
datastorePreferences = "1.0.0"
flowCombinetupleKt = "1.2.0"
jsoup = "1.14.3"
jsoupVersion = "1.16.1"
kotlinxCoroutinesAndroid = "1.7.3"
kotlinxCoroutinesGuava = "1.7.3"
kotlinxSerializationJsonOkio = "1.5.1"
ktorClientOkhttp = "2.3.3"
ktorServerRateLimit = "2.3.3"
lifecycleRuntimeCompose = "2.6.2"
lifecycleRuntimeKtx = "2.6.2"
material = "1.10.0"
material3WindowSizeClass = "1.1.2"
materialIconsExtended = "1.5.4"
materialVersion = "1.5.4"
navVersion = "2.7.5"
okhttp = "4.12.0"
okhttpDnsoverhttps = "4.11.0"
okio = "3.6.0"
orbital = "0.2.4"
pagingCommon = "3.2.1"
pagingCompose = "3.2.1"
pagingRuntime = "3.2.1"
roomPaging = "2.6.0"
testJunit = "1.1.5"
junit= "4.13.2"
koinVersion="3.5.0"
koinCompose="3.5.0"
coil = "2.4.0"
tokenBucket = "1.2"
tuplesKt = "1.2.0"
voyager="1.0.0-rc10"
ktor="2.3.1"
kotlinserialization="1.5.1"
kotlinxdatetime="0.4.1"
room_version = "2.6.0"
workGcm = "2.9.0-rc01"
workMultiprocess = "2.9.0-rc01"
workRuntimeKtx = "2.9.0-rc01"
workRuntimeKtxVersion = "2.8.1"
workRxjava2 = "2.9.0-rc01"
workTesting = "2.9.0-rc01"
agp = "8.1.4"
uiautomator = "2.2.0"
benchmark-macro-junit4 = "1.2.1"
org-jetbrains-kotlin-android = "1.9.20"
org-jetbrains-kotlin-jvm = "1.9.20"

[libraries]
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanistWebview" }
accompanist-webview-0_30_1 = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanistWebviewVersion" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-core-ktx = { module ="androidx.core:core-ktx", version.ref="androidxCoreKtx" }
androidx-compose-ui = { module="androidx.compose.ui:ui" }
androidx-compose-ui-graphics= { module="androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling= { module ="androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3= { module="androidx.compose.material3:material3" }
androidx-compose-ui-manifest={module="androidx.compose.ui:ui-test-manifest"}
androidx-compose-ui-test-junit={module="androidx.compose.ui:ui-test-junit4"}
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "pagingCommon" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomPaging" }
androidx-work-gcm = { module = "androidx.work:work-gcm", version.ref = "workGcm" }
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workMultiprocess" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-work-runtime-ktx-2_8_1 = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtxVersion" }
androidx-work-rxjava2 = { module = "androidx.work:work-rxjava2", version.ref = "workRxjava2" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workTesting" }
coil-svg={module="io.coil-kt:coil-svg", version.ref="coil"}

flow-combinetuple-kt = { module = "com.github.Zhuinden:flow-combinetuple-kt", version.ref = "flowCombinetupleKt" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
jsoup-1_16_1 = { module = "org.jsoup:jsoup", version.ref = "jsoupVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinxCoroutinesGuava" }
kotlinx-datetime={module="org.jetbrains.kotlinx:kotlinx-datetime", version.ref="kotlinxdatetime"}

koin-core={module="io.insert-koin:koin-core", version.ref="koinVersion"}
koin-android={module="io.insert-koin:koin-android", version.ref="koinVersion"}
koin-compose={module="io.insert-koin:koin-androidx-compose", version.ref="koinCompose"}
koin-navigation={module="io.insert-koin:koin-androidx-navigation", version.ref="koinVersion"}
koin-workmanager={module="io.insert-koin:koin-androidx-workmanager", version.ref="koinVersion"}

kotlinx-serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "kotlinxSerializationJsonOkio" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-server-rate-limit = { module = "io.ktor:ktor-server-rate-limit", version.ref = "ktor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-dnsoverhttps = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttpDnsoverhttps" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
orbital = { module = "com.github.skydoves:orbital", version.ref = "orbital" }
room-runtime={module="androidx.room:room-runtime", version.ref="room_version"}
room-compiler={module="androidx.room:room-compiler", version.ref="room_version"}
room-coroutines={module="androidx.room:room-ktx", version.ref="room_version"}
room-test={module="androidx.room:room-testing", version.ref="room_version"}
room-ksp={module="androidx.room:room-compiler", version.ref="room_version"}

androidx-test-espresso-core= { module="androidx.test.espresso:espresso-core", version.ref="androidxTestEspressoCore"}
androidx-test-junit = {module = "androidx.test.ext:junit", version.ref="testJunit"}
junit={module = "junit:junit", version.ref ="junit"}

token-bucket = { module = "org.isomorphism:token-bucket", version.ref = "tokenBucket" }
tuples-kt = { module = "com.github.Zhuinden:tuples-kt", version.ref = "tuplesKt" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-bottomSheetNavigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-androidx = { module = "cafe.adriel.voyager:voyager-androidx", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
coil = {module ="io.coil-kt:coil", version.ref="coil" }
coil-compose = {module="io.coil-kt:coil-compose", version.ref="coil" }

ktor-core={module="io.ktor:ktor-client-core", version.ref="ktor" }
ktor-cio={module="io.ktor:ktor-client-cio", version.ref="ktor"}
ktor-websockets={module="io.ktor:ktor-client-websockets", version.ref="ktor"}
ktor-serialization-json={module="io.ktor:ktor-serialization-kotlinx-json", version.ref="ktor"}
kotlin-serialization={module="org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref="kotlinserialization"}
ktor-logging={module="io.ktor:ktor-client-logging", version.ref="ktor"}
ktor-contentnegotiation={module="io.ktor:ktor-client-content-negotiation", version.ref="ktor"}
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }

[plugins]
com-android-test = { id = "com.android.test", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
